### ISSUE TITLE
Incorrect setup instructions on PyPi

### ISSUE THREAD

**Issue by cremsburg** [nautobot/nautobot-plugin-nornir#17]
### Environment
* Python version: 3.8 
* Nautobot version: 1.0.0 
* nautobot-plugin-nornir version: 0.9.0 

The documentation hosted on PyPi incorrectly refers to the package name as `nautobot_nornir` for both the plugin and plugins_config sections

### Steps to Reproduce
1. open a web browser
2. visit pypi page https://pypi.org/project/nautobot-plugin-nornir/
3. look at the documentation

### Expected Behavior
Expected to read "nautobot_plugin_nornir"

Oberved reading "nautobot_nornir"

**Comment by itdependsnetworks** [comment]
This was addressed in #14 waiting for next release until it shows up in pypi.
