### ISSUE TITLE
CredentialsSettingsVars  "There was no username defined, preemptively failed"

### ISSUE THREAD

**Issue by dd1245** [nautobot/nautobot-plugin-nornir#28]
### Environment
* Python version:  3.6.8
* Nautobot version:  1.1.2
* nautobot-plugin-nornir version:  0.9.4

### Steps to Reproduce
1. Use the CredentialsSettingsVars and defined credentials in the nautobot_config.py
2. Attempt to backup a config (in my case Juniper)

### Expected Behavior
Backup of configuration using credentials defined

### Observed Behavior
It appears to select the correct platform but is not using the defined credentials as per the below

Executing dispatcher for cpe1 (juniper_junos)
Found driver nornir_nautobot.plugins.tasks.dispatcher.juniper_junos.NautobotNornirDriver
There was no username defined, preemptively failed

**Comment by itdependsnetworks** [comment]
Is it all platforms, or just the juniper_junos platform?
Can you provide the details for everything, such as how you set CredentialsSettingsVars in the config, how you set the user/pass, etc.

**Comment by dd1245** [comment]
Hi.

I only have Cisco IOS and Juniper devices, but it affects both platforms. Here is how I configured the nautobot configuration.

PLUGINS_CONFIG = {
    "nautobot_plugin_nornir": {
        "nornir_settings": {
            "credentials": "nautobot_plugin_nornir.plugins.credentials.settings_vars.CredentialsSettingsVars",
            "runner": {
                "plugin": "threaded",
                "options": {
                    "num_workers": 20,
                },
            },
    "dispatcher_mapping": None,
    "username": "user@test",
    "password": "replacedpw",
    "secret": "replacedpw",
        },
    },
    "nautobot_golden_config": {
        "per_feature_bar_width": 0.15,
        "per_feature_width": 13,
        "per_feature_height": 4,
        "enable_backup": True,
        "enable_compliance": True,
        "enable_intended": True,
        "enable_sotagg": True,
        "sot_agg_transposer": None,
        "platform_slug_map": None,
    },
}

**Comment by itdependsnetworks** [comment]
I edited your comment to make readable, I can see now that you do not have the expected structure, username and password are under `PLUGINS_CONFIG["nautobot_plugin_nornir"]["nornir_settings"]["username"]` whereas the should be under `PLUGINS_CONFIG["nautobot_plugin_nornir"]["username"]`.

**Comment by dd1245** [comment]
That's working fine now. 

Thank you.
