### ISSUE TITLE
Allow users to provide extra netmiko and Napalm settings

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-nornir#40]
### Environment
* Python version:  3.7
* Nautobot version:  11.1.6
* nautobot-plugin-nornir version:  0.9.7

### Proposed Functionality
Netmiko and Napalm connection plugins for Nornir both support some additional parameters via the `extras` section of the connection plugin.
The proposal is to extend the Nornir Inventory to allow uses to specific a list of extras parameters and pass them to Nornir. 
See below an example of what the configuration could look like 

```python
PLUGINS_CONFIG = {
  "nautobot_plugin_nornir": {
    "napalm_extras": {
         .. 
     },
    "netmiko_extras": {
      "global_delay_factor": 5,
      "banner_timeout":  40, 
      "conn_timeout": 30,
      },
    },
  }
```

### Use Case
Allow users to customize Netmiko and Napalm behavior. One of the primary use case is to adjust some timers and timeout `conn_timeout` etc ..

**Comment by jeffkala** [comment]
@dgarros should this be more granular for any reason?  Meaning maybe you can set these "extras" per platform slug or something?  I could think of scenarios where maybe you want to extend `global_delay_factor` for a certain platform not globally.

**Comment by dgarros** [comment]
There might be a use case for that but not sure how that would look like
Maybe we could leverage the config context here ?
